spring.application.name=haircut-appointments
server.port=${SERVER_PORT:8090}
spring.config.import=optional:file:./application-secrets.properties,optional:file:./application-admin-secrets.properties

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/haircut_appointments}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true
spring.jackson.deserialization.fail-on-unknown-properties=true
