import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { api, type Appointment, type AvailabilitySlot, type Professional, type Service } from './api'
import './App.css'
import './Admin.css'
import './Forms.css'
import './Luxury.css'

type BookingState = { service?: Service; professional?: Professional; date?: string; slot?: AvailabilitySlot; appointment?: Appointment }
type BookingContextValue = BookingState & { update: (next: Partial<BookingState>) => void; reset: () => void }
const BookingContext = createContext<BookingContextValue | null>(null)
const useBooking = () => useContext(BookingContext)!
const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value)
const time = (value: string) => new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date(value))
const fullDate = (value: string) => new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(new Date(`${value}T12:00:00`))

function Layout() {
  const [menuOpen, setMenuOpen] = useState(false)
  const location = useLocation()
  return <>
    <header className="site-header">
      <Link className="brand" to="/" onClick={() => setMenuOpen(false)}><span className="brand-mark">A</span><span>Atelier</span><small>Hair & Beauty</small></Link>
      <button className="menu-toggle" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>☰</button>
      <nav className={menuOpen ? 'open' : ''}><Link to="/services">Services</Link><Link to="/appointments">My appointment</Link><Link to="/admin">Team login</Link><Link className="nav-cta" to="/book/service">Book now</Link></nav>
    </header>
    <main>{location.pathname !== '/' && <Link className="back-home global-back" to="/"><span>←</span> Back to home</Link>}<Routes>
      <Route path="/" element={<Home />} /><Route path="/services" element={<ServiceSelection standalone />} /><Route path="/book/service" element={<ServiceSelection />} /><Route path="/book/professional" element={<ProfessionalSelection />} /><Route path="/book/date" element={<DateSelection />} /><Route path="/book/details" element={<BookingForm />} /><Route path="/confirmation" element={<Confirmation />} /><Route path="/appointments" element={<AppointmentLookup />} /><Route path="/admin" element={<Admin />} /><Route path="*" element={<Navigate to="/" replace />} />
    </Routes></main>
    <footer><div><Link className="brand footer-brand" to="/"><span className="brand-mark">A</span><span>Atelier</span><small>Hair & Beauty</small></Link></div><div><p>Quiet luxury. Exceptional craft.</p><span>Chicago, Illinois · Tue–Sun</span></div><div className="footer-links"><Link to="/services">Services</Link><Link to="/appointments">Manage booking</Link></div><p className="copyright">© {new Date().getFullYear()} Atelier Hair & Beauty</p></footer>
  </>
}

function Home() {
  return <>
    <section className="hero-section"><div className="hero-copy"><p className="eyebrow">A modern beauty atelier</p><h1>Your ritual.<br/><em>Refined.</em></h1><p className="hero-lede">Expert hair and beauty services, considered down to the final detail. Created for how you want to feel.</p><div className="hero-actions"><Link className="button primary" to="/book/service">Book an appointment</Link><Link className="text-link" to="/services">Explore services <span>→</span></Link></div><div className="hero-proof"><span>★★★★★</span><p><strong>4.9</strong> from 280+ guests</p></div></div><div className="hero-image"><div className="image-label"><span>01</span><p>Personalized care<br/>from consultation to finish</p></div></div></section>
    <section className="manifesto"><p className="eyebrow">The Atelier standard</p><h2>Beauty is personal.<br/>The experience should be, too.</h2><p>We pair technical expertise with unrushed attention, creating an experience that feels effortless and entirely your own.</p></section>
    <section className="feature-grid"><article className="feature feature-image-one"><span>Hair</span></article><article className="feature feature-copy"><p className="eyebrow">01 · Tailored</p><h3>Cut & style</h3><p>Shape, movement, and finish designed around you.</p><Link to="/book/service">Discover hair services →</Link></article><article className="feature feature-copy dark"><p className="eyebrow">02 · Restorative</p><h3>Skin & beauty</h3><p>Considered treatments that restore your natural radiance.</p><Link to="/book/service">Discover beauty services →</Link></article><article className="feature feature-image-two"><span>Beauty</span></article></section>
    <section className="closing-cta"><p className="eyebrow">Your time, beautifully spent</p><h2>Ready for your next ritual?</h2><Link className="button light" to="/book/service">Reserve your appointment</Link></section>
  </>
}

function StepHeader({ step, title, text }: { step: number; title: string; text: string }) { return <div className="flow-header"><p className="eyebrow">Step {step} of 4</p><h1>{title}</h1><p>{text}</p><div className="progress"><i style={{ width: `${step * 25}%` }}/></div></div> }

function ServiceSelection({ standalone = false }: { standalone?: boolean }) {
  const [services, setServices] = useState<Service[]>([]); const [audience, setAudience] = useState<'ALL' | 'MEN' | 'WOMEN'>('ALL'); const [error, setError] = useState(''); const { update } = useBooking(); const navigate = useNavigate()
  useEffect(() => { api.services().then(setServices).catch(e => setError(e.message)) }, [])
  return <section className="flow-page">{standalone ? <div className="flow-header"><p className="eyebrow">Our menu</p><h1>Services & pricing</h1><p>Expert care, transparent pricing, and time reserved just for you.</p></div> : <StepHeader step={1} title="Choose your service" text="Begin with the ritual that feels right for you." />}<div className="filter-tabs">{(['ALL','MEN','WOMEN'] as const).map(value => <button className={audience === value ? 'active' : ''} onClick={() => setAudience(value)} key={value}>{value === 'ALL' ? 'All services' : `For ${value.toLowerCase()}`}</button>)}</div>{error && <Notice message={error} />}<div className="service-list">{services.filter(item => audience === 'ALL' || item.audience === audience).map(service => <button className="service-card" key={service.id} onClick={() => { update({ service, professional: undefined, date: undefined, slot: undefined }); navigate('/book/professional') }}><span className="service-icon">{service.type.includes('HAIR') ? '✦' : '◇'}</span><span className="service-main"><strong>{service.displayName}</strong><small>{service.audience === 'MEN' ? "Men's collection" : "Women's collection"} · {service.durationMinutes} min</small></span><span className="service-price">{money(service.price)}</span><span className="arrow">→</span></button>)}</div></section>
}

function ProfessionalSelection() {
  const { service, update } = useBooking(); const [items, setItems] = useState<Professional[]>([]); const [error, setError] = useState(''); const navigate = useNavigate()
  useEffect(() => { if (service) api.professionals(service.id).then(setItems).catch(e => setError(e.message)) }, [service])
  if (!service) return <Navigate to="/book/service" replace />
  return <section className="flow-page"><StepHeader step={2} title="Choose your professional" text={`Select a specialist for your ${service.displayName.toLowerCase()}.`} /><SelectionSummary service={service} />{error && <Notice message={error} />}<div className="professional-grid">{items.map((item, index) => <button className="professional-card" key={item.id} onClick={() => { update({ professional: item, date: undefined, slot: undefined }); navigate('/book/date') }}><div className={`portrait portrait-${index % 3}`}><span>{item.name.split(' ').map(n => n[0]).join('')}</span></div><div><strong>{item.name}</strong><small>Senior professional</small><p>{item.bio}</p><span className="choose-link">Choose {item.name.split(' ')[0]} →</span></div></button>)}</div></section>
}

function DateSelection() {
  const { service, professional, date, update } = useBooking(); const [selectedDate, setSelectedDate] = useState(date ?? ''); const [slots, setSlots] = useState<AvailabilitySlot[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const navigate = useNavigate(); const today = new Date().toISOString().slice(0, 10)
  useEffect(() => { if (!selectedDate || !service || !professional) return; setLoading(true); setError(''); setSlots([]); api.availability(professional.id, service.id, selectedDate).then(setSlots).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [selectedDate, service, professional])
  if (!service || !professional) return <Navigate to="/book/service" replace />
  return <section className="flow-page"><StepHeader step={3} title="Choose a date & time" text="Only times currently available with your professional are shown." /><SelectionSummary service={service} professional={professional} /><div className="date-time-panel"><label className="date-picker"><span>Appointment date</span><input type="date" min={today} value={selectedDate} onChange={e => { setSelectedDate(e.target.value); update({ date: e.target.value, slot: undefined }) }} /></label><div className="time-area"><h3>{selectedDate ? fullDate(selectedDate) : 'Select a date'}</h3>{loading && <p className="muted">Finding available times…</p>}{error && <Notice message={error} />}{!loading && selectedDate && !error && slots.length === 0 && <p className="muted">No availability on this date. Please choose another day.</p>}<div className="time-grid">{slots.map(slot => <button key={slot.startTime} onClick={() => { update({ date: selectedDate, slot }); navigate('/book/details') }}>{time(slot.startTime)}</button>)}</div></div></div></section>
}

function BookingForm() {
  const { service, professional, date, slot, update } = useBooking(); const [form, setForm] = useState({ name: '', email: '', phone: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const navigate = useNavigate()
  if (!service || !professional || !date || !slot) return <Navigate to="/book/service" replace />
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const appointment = await api.book({ customerName: form.name, customerEmail: form.email, customerPhone: form.phone, professionalId: professional.id, serviceId: service.id, startTime: slot.startTime }); update({ appointment }); navigate('/confirmation') } catch (e) { setError(e instanceof Error ? e.message : 'Booking could not be completed.') } finally { setSaving(false) } }
  return <section className="flow-page"><StepHeader step={4} title="A few final details" text="Tell us where to send your appointment confirmation." /><div className="booking-layout"><form className="booking-form" onSubmit={submit}>{error && <Notice message={error} />}<label>Full name<input required minLength={2} value={form.name} onChange={e => setForm({...form, name: e.target.value})} placeholder="Your full name" /></label><label>Email address<input required type="email" value={form.email} onChange={e => setForm({...form, email: e.target.value})} placeholder="you@example.com" /></label><label>Phone number<input required type="tel" value={form.phone} onChange={e => setForm({...form, phone: e.target.value})} placeholder="(312) 555-0123" /></label><button className="button primary wide" disabled={saving}>{saving ? 'Reserving…' : 'Confirm appointment'}</button><small>By confirming, you agree to our booking and cancellation policy.</small></form><AppointmentCard service={service} professional={professional} startTime={slot.startTime} /></div></section>
}

function Confirmation() {
  const { appointment, reset } = useBooking(); if (!appointment) return <Navigate to="/" replace />
  return <section className="confirmation-page"><div className="confirmation-check">✓</div><p className="eyebrow">Appointment confirmed</p><h1>We’ll see you soon.</h1><p>Your ritual is reserved. Keep your confirmation number to manage your booking.</p><div className="confirmation-number"><span>Confirmation number</span><strong>{appointment.confirmationNumber}</strong></div><AppointmentDetails appointment={appointment} /><div className="confirmation-actions"><Link className="button primary" to="/appointments" onClick={reset}>Manage appointment</Link><Link className="text-link" to="/" onClick={reset}>Return home</Link></div></section>
}

function AppointmentLookup() {
  const [credentials, setCredentials] = useState({ confirmationNumber: '', email: '' }); const [appointment, setAppointment] = useState<Appointment | null>(null); const [slots, setSlots] = useState<AvailabilitySlot[]>([]); const [rescheduleOpen, setRescheduleOpen] = useState(false); const [date, setDate] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const lookup = async (event: FormEvent) => { event.preventDefault(); setError(''); setMessage(''); try { setAppointment(await api.lookup(credentials.confirmationNumber, credentials.email)) } catch (e) { setError(e instanceof Error ? e.message : 'Appointment not found.') } }
  const cancel = async () => { if (!confirm('Cancel this appointment? This action cannot be undone.')) return; try { setAppointment(await api.cancel(credentials.confirmationNumber, credentials.email)); setMessage('Your appointment has been cancelled.') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to cancel.') } }
  const loadSlots = async (value: string) => { setDate(value); if (!appointment) return; try { setSlots(await api.availability(appointment.professionalId, appointment.serviceId, value)) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load times.') } }
  const reschedule = async (startTime: string) => { try { setAppointment(await api.reschedule(credentials.confirmationNumber, credentials.email, startTime)); setRescheduleOpen(false); setMessage('Your appointment has been rescheduled.') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to reschedule.') } }
  return <section className="lookup-page"><div className="lookup-intro"><p className="eyebrow">Your appointment</p><h1>View or manage your booking.</h1><p>Enter the details from your confirmation to cancel or choose a new time.</p></div>{!appointment ? <form className="lookup-form" onSubmit={lookup}><label>Confirmation number<input required value={credentials.confirmationNumber} onChange={e => setCredentials({...credentials, confirmationNumber: e.target.value.toUpperCase()})} placeholder="ATL-XXXXXXXX" /></label><label>Email address<input required type="email" value={credentials.email} onChange={e => setCredentials({...credentials, email: e.target.value})} placeholder="you@example.com" /></label>{error && <Notice message={error} />}<button className="button primary wide">Find appointment</button></form> : <div className="managed-booking">{message && <div className="success-notice">{message}</div>}<AppointmentDetails appointment={appointment} />{appointment.status === 'BOOKED' && <div className="manage-actions"><button className="button primary" onClick={() => setRescheduleOpen(!rescheduleOpen)}>Reschedule</button><button className="button danger" onClick={cancel}>Cancel appointment</button></div>}{rescheduleOpen && <div className="reschedule-panel"><h3>Choose a new date</h3><input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e => loadSlots(e.target.value)} /><div className="time-grid">{slots.map(slot => <button key={slot.startTime} onClick={() => reschedule(slot.startTime)}>{time(slot.startTime)}</button>)}</div></div>}<button className="text-link" onClick={() => { setAppointment(null); setMessage('') }}>Look up another booking</button></div>}</section>
}

function Admin() {
  const [authenticated, setAuthenticated] = useState(Boolean(sessionStorage.getItem('atelier_token')))
  const [credentials, setCredentials] = useState({ username: '', password: '' }); const [error, setError] = useState('')
  const login = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const result=await api.login(credentials.username,credentials.password); sessionStorage.setItem('atelier_token',result.token); sessionStorage.setItem('atelier_user',result.username); setAuthenticated(true) } catch(e){setError(e instanceof Error?e.message:'Unable to sign in.')} }
  if (!authenticated) return <section className="admin-login"><div><p className="eyebrow">Atelier team</p><h1>Welcome back.</h1><p>Secure access for administrators and professionals.</p></div><form onSubmit={login}><label>Username<input required autoComplete="username" value={credentials.username} onChange={e=>setCredentials({...credentials,username:e.target.value})}/></label><label>Password<input required type="password" autoComplete="current-password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/></label>{error&&<Notice message={error}/>}<button className="button primary wide">Sign in</button></form></section>
  return <AdminDashboard onLogout={()=>{sessionStorage.removeItem('atelier_token');sessionStorage.removeItem('atelier_user');setAuthenticated(false)}} />
}

function AdminDashboard({onLogout}:{onLogout:()=>void}) {
  const today=new Date().toISOString().slice(0,10); const end=new Date(Date.now()+30*86400000).toISOString().slice(0,10)
  const [appointments,setAppointments]=useState<Appointment[]>([]); const [services,setServices]=useState<Service[]>([]); const [professionals,setProfessionals]=useState<Professional[]>([]); const [tab,setTab]=useState<'appointments'|'services'|'professionals'>('appointments'); const [error,setError]=useState('')
  const load=()=>Promise.all([api.adminAppointments(today,end),api.services(),api.adminProfessionals()]).then(([a,s,p])=>{setAppointments(a);setServices(s);setProfessionals(p)}).catch(e=>setError(e.message))
  useEffect(()=>{load()},[])
  const status=async(id:number,value:Appointment['status'])=>{try{await api.updateStatus(id,value);load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}}
  return <section className="admin-page"><header className="admin-head"><div><p className="eyebrow">Operations</p><h1>Studio dashboard</h1><p>{new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date())}</p></div><button className="text-link" onClick={onLogout}>Sign out</button></header><div className="admin-tabs"><button className={tab==='appointments'?'active':''} onClick={()=>setTab('appointments')}>Appointments</button><button className={tab==='services'?'active':''} onClick={()=>setTab('services')}>Services</button><button className={tab==='professionals'?'active':''} onClick={()=>setTab('professionals')}>Professionals</button></div>{error&&<Notice message={error}/>}<div className="metrics"><article><span>Upcoming</span><strong>{appointments.filter(a=>a.status==='BOOKED').length}</strong></article><article><span>Completed</span><strong>{appointments.filter(a=>a.status==='COMPLETED').length}</strong></article><article><span>Professionals</span><strong>{professionals.filter(p=>p.active).length}</strong></article></div>
    {tab==='appointments'&&<div className="admin-list">{appointments.map(item=><article key={item.id}><div className="admin-time"><strong>{time(item.startTime)}</strong><span>{item.startTime.slice(0,10)}</span></div><div><strong>{item.customerName}</strong><span>{item.serviceType.replaceAll('_',' ')} with {item.professionalName}</span></div><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span><select aria-label={`Status for ${item.customerName}`} value={item.status} onChange={e=>status(item.id,e.target.value as Appointment['status'])}><option>BOOKED</option><option>COMPLETED</option><option>NO_SHOW</option><option>CANCELLED</option></select></article>)}</div>}
    {tab==='services'&&<ServiceAdmin services={services} refresh={load}/>} {tab==='professionals'&&<ProfessionalAdmin services={services} professionals={professionals} refresh={load}/>}</section>
}

function ServiceAdmin({services,refresh}:{services:Service[];refresh:()=>unknown}) {
  const [form,setForm]=useState({audience:'MEN' as 'MEN'|'WOMEN',type:'HAIRCUT',price:40,durationMinutes:30}); const [error,setError]=useState('')
  const submit=async(e:FormEvent)=>{e.preventDefault();try{await api.createService(form);refresh()}catch(x){setError(x instanceof Error?x.message:'Unable to save')}}
  return <div className="management-grid"><form className="management-form" onSubmit={submit}><h3>Add service</h3><label>Audience<select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value as 'MEN'|'WOMEN'})}><option>MEN</option><option>WOMEN</option></select></label><label>Service type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['HAIRCUT','BEARD_TRIM','HAIR_AND_BEARD','HAIR_STYLING','WAXING','THREADING','FACIAL','CLEANSING','MAKEUP','NAILS'].map(v=><option key={v}>{v}</option>)}</select></label><label>Price<input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>Duration<input type="number" min="15" step="15" value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:Number(e.target.value)})}/></label>{error&&<Notice message={error}/>}<button className="button primary">Add service</button></form><div className="catalog-table">{services.map(s=><article key={s.id}><div><strong>{s.displayName}</strong><span>{s.audience} · {s.durationMinutes} min</span></div><strong>{money(s.price)}</strong></article>)}</div></div>
}

function ProfessionalAdmin({services,professionals,refresh}:{services:Service[];professionals:Professional[];refresh:()=>unknown}) {
  const [form,setForm]=useState({name:'',bio:'',serviceId:''}); const [hours,setHours]=useState({professionalId:'',day:'MONDAY',startTime:'09:00',endTime:'18:00'}); const [away,setAway]=useState({professionalId:'',startsAt:'',endsAt:'',reason:''}); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  const submit=async(e:FormEvent)=>{e.preventDefault();try{await api.createProfessional({name:form.name,bio:form.bio,active:true,serviceIds:[Number(form.serviceId)]});setForm({name:'',bio:'',serviceId:''});refresh()}catch(x){setError(x instanceof Error?x.message:'Unable to save')}}
  const saveHours=async(e:FormEvent)=>{e.preventDefault();try{await api.setWorkingHours(Number(hours.professionalId),hours.day,hours.startTime,hours.endTime);setMessage('Working hours updated.')}catch(x){setError(x instanceof Error?x.message:'Unable to save')}}
  const saveAway=async(e:FormEvent)=>{e.preventDefault();try{await api.addTimeOff(Number(away.professionalId),away.startsAt,away.endsAt,away.reason);setMessage('Time off added.')}catch(x){setError(x instanceof Error?x.message:'Unable to save')}}
  const options=professionals.map(p=><option value={p.id} key={p.id}>{p.name}</option>)
  return <div className="management-grid"><div className="form-stack"><form className="management-form" onSubmit={submit}><h3>Add professional</h3><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Bio<textarea required value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><label>Primary service<select required value={form.serviceId} onChange={e=>setForm({...form,serviceId:e.target.value})}><option value="">Choose service</option>{services.map(s=><option value={s.id} key={s.id}>{s.displayName} · {s.audience}</option>)}</select></label><button className="button primary">Add professional</button></form><form className="management-form" onSubmit={saveHours}><h3>Working hours</h3><label>Professional<select required value={hours.professionalId} onChange={e=>setHours({...hours,professionalId:e.target.value})}><option value="">Choose professional</option>{options}</select></label><label>Day<select value={hours.day} onChange={e=>setHours({...hours,day:e.target.value})}>{['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'].map(day=><option key={day}>{day}</option>)}</select></label><div className="form-row"><label>Opens<input type="time" value={hours.startTime} onChange={e=>setHours({...hours,startTime:e.target.value})}/></label><label>Closes<input type="time" value={hours.endTime} onChange={e=>setHours({...hours,endTime:e.target.value})}/></label></div><button className="button primary">Save hours</button></form><form className="management-form" onSubmit={saveAway}><h3>Schedule time off</h3><label>Professional<select required value={away.professionalId} onChange={e=>setAway({...away,professionalId:e.target.value})}><option value="">Choose professional</option>{options}</select></label><label>Starts<input type="datetime-local" required value={away.startsAt} onChange={e=>setAway({...away,startsAt:e.target.value})}/></label><label>Ends<input type="datetime-local" required value={away.endsAt} onChange={e=>setAway({...away,endsAt:e.target.value})}/></label><label>Reason<input value={away.reason} onChange={e=>setAway({...away,reason:e.target.value})}/></label><button className="button primary">Add time off</button></form>{error&&<Notice message={error}/>} {message&&<div className="success-notice">{message}</div>}</div><div className="catalog-table">{professionals.map(p=><article key={p.id}><div><strong>{p.name}</strong><span>{p.bio}</span></div><span className={`status ${p.active?'booked':'cancelled'}`}>{p.active?'ACTIVE':'INACTIVE'}</span></article>)}</div></div>
}

function SelectionSummary({ service, professional }: { service: Service; professional?: Professional }) { return <div className="selection-summary"><span>{service.displayName}</span><span>{service.durationMinutes} min</span><span>{money(service.price)}</span>{professional && <span>with {professional.name}</span>}</div> }
function AppointmentCard({ service, professional, startTime }: { service: Service; professional: Professional; startTime: string }) { return <aside className="appointment-card"><p className="eyebrow">Your reservation</p><h3>{service.displayName}</h3><dl><div><dt>Professional</dt><dd>{professional.name}</dd></div><div><dt>Date</dt><dd>{fullDate(startTime.slice(0,10))}</dd></div><div><dt>Time</dt><dd>{time(startTime)} · {service.durationMinutes} min</dd></div><div><dt>Total</dt><dd>{money(service.price)}</dd></div></dl></aside> }
function AppointmentDetails({ appointment }: { appointment: Appointment }) { return <div className="appointment-details"><div className="status-line"><span className={`status ${appointment.status.toLowerCase()}`}>{appointment.status}</span><span>{appointment.confirmationNumber}</span></div><h2>{appointment.serviceType.replaceAll('_',' ')}</h2><dl><div><dt>Professional</dt><dd>{appointment.professionalName}</dd></div><div><dt>Date</dt><dd>{fullDate(appointment.startTime.slice(0,10))}</dd></div><div><dt>Time</dt><dd>{time(appointment.startTime)} · {appointment.durationMinutes} min</dd></div><div><dt>Price</dt><dd>{money(appointment.price)}</dd></div></dl></div> }
function Notice({ message }: { message: string }) { return <div className="notice" role="alert">{message}</div> }

export default function App() {
  const [booking, setBooking] = useState<BookingState>({}); const value = useMemo(() => ({ ...booking, update: (next: Partial<BookingState>) => setBooking(current => ({ ...current, ...next })), reset: () => setBooking({}) }), [booking])
  return <BookingContext.Provider value={value}><BrowserRouter><Layout /></BrowserRouter></BookingContext.Provider>
}
