CREATE TABLE salons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    time_zone VARCHAR(50) NOT NULL
);

INSERT INTO salons (id, name, slug, active, time_zone)
VALUES (1, 'Atelier Hair & Beauty', 'atelier-hair-beauty', TRUE, 'America/Chicago');

SELECT setval(pg_get_serial_sequence('salons', 'id'), 1, TRUE);

ALTER TABLE services ADD COLUMN salon_id BIGINT;
ALTER TABLE professionals ADD COLUMN salon_id BIGINT;
ALTER TABLE appointments ADD COLUMN salon_id BIGINT;
ALTER TABLE user_accounts ADD COLUMN salon_id BIGINT;

UPDATE services SET salon_id = 1;
UPDATE professionals SET salon_id = 1;
UPDATE appointments SET salon_id = 1;
UPDATE user_accounts SET salon_id = 1;

ALTER TABLE services ALTER COLUMN salon_id SET NOT NULL;
ALTER TABLE professionals ALTER COLUMN salon_id SET NOT NULL;
ALTER TABLE appointments ALTER COLUMN salon_id SET NOT NULL;
ALTER TABLE user_accounts ALTER COLUMN salon_id SET NOT NULL;

ALTER TABLE services ADD CONSTRAINT fk_services_salon FOREIGN KEY (salon_id) REFERENCES salons(id);
ALTER TABLE professionals ADD CONSTRAINT fk_professionals_salon FOREIGN KEY (salon_id) REFERENCES salons(id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_salon FOREIGN KEY (salon_id) REFERENCES salons(id);
ALTER TABLE user_accounts ADD CONSTRAINT fk_user_accounts_salon FOREIGN KEY (salon_id) REFERENCES salons(id);

ALTER TABLE services DROP CONSTRAINT IF EXISTS uk_service_audience_type;
ALTER TABLE services ADD CONSTRAINT uk_service_salon_audience_type UNIQUE (salon_id, audience, service_type);
ALTER TABLE services ADD CONSTRAINT uk_services_salon_id_id UNIQUE (salon_id, id);
ALTER TABLE professionals ADD CONSTRAINT uk_professionals_salon_id_id UNIQUE (salon_id, id);

ALTER TABLE appointments ADD CONSTRAINT fk_appointments_salon_professional
    FOREIGN KEY (salon_id, professional_id) REFERENCES professionals(salon_id, id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_salon_service
    FOREIGN KEY (salon_id, service_id) REFERENCES services(salon_id, id);
ALTER TABLE user_accounts ADD CONSTRAINT fk_accounts_salon_professional
    FOREIGN KEY (salon_id, professional_id) REFERENCES professionals(salon_id, id);

CREATE INDEX idx_services_salon ON services(salon_id);
CREATE INDEX idx_professionals_salon ON professionals(salon_id);
CREATE INDEX idx_appointments_salon_start ON appointments(salon_id, start_time);

CREATE OR REPLACE FUNCTION enforce_professional_service_salon() RETURNS trigger AS $$
BEGIN
    IF (SELECT salon_id FROM professionals WHERE id = NEW.professional_id)
       IS DISTINCT FROM (SELECT salon_id FROM services WHERE id = NEW.service_id) THEN
        RAISE EXCEPTION 'Professional and service must belong to the same salon';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_professional_service_salon
BEFORE INSERT OR UPDATE ON professional_services
FOR EACH ROW EXECUTE FUNCTION enforce_professional_service_salon();
