CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(25) NOT NULL,
    email VARCHAR(254) NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    CONSTRAINT uk_appointment_slot UNIQUE (appointment_date, appointment_time)
);
