CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audience VARCHAR(10) NOT NULL,
    service_type VARCHAR(30) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    CONSTRAINT ck_service_audience CHECK (audience IN ('MEN', 'WOMEN')),
    CONSTRAINT ck_service_type CHECK (
        (audience = 'MEN' AND service_type IN ('HAIRCUT', 'BEARD_TRIM', 'HAIR_AND_BEARD'))
        OR
        (audience = 'WOMEN' AND service_type IN (
            'HAIRCUT', 'HAIR_STYLING', 'WAXING', 'THREADING', 'FACIAL',
            'CLEANSING', 'MAKEUP', 'NAILS'
        ))
    ),
    CONSTRAINT ck_service_price CHECK (price >= 0),
    CONSTRAINT ck_service_duration CHECK (duration_minutes > 0),
    CONSTRAINT uk_service_audience_type UNIQUE (audience, service_type)
);
