CREATE TABLE professionals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    bio VARCHAR(2000) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE professional_services (
    professional_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    CONSTRAINT pk_professional_services PRIMARY KEY (professional_id, service_id),
    CONSTRAINT fk_professional_services_professional
        FOREIGN KEY (professional_id) REFERENCES professionals (id) ON DELETE CASCADE,
    CONSTRAINT fk_professional_services_service
        FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE
);

CREATE INDEX idx_professional_services_service_id
    ON professional_services (service_id);
