CREATE TABLE professional_working_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT fk_working_hours_professional
        FOREIGN KEY (professional_id) REFERENCES professionals (id) ON DELETE CASCADE,
    CONSTRAINT uk_professional_working_day UNIQUE (professional_id, day_of_week),
    CONSTRAINT ck_working_hours_day CHECK (day_of_week IN (
        'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
        'FRIDAY', 'SATURDAY', 'SUNDAY'
    )),
    CONSTRAINT ck_working_hours_time CHECK (end_time > start_time)
);

INSERT INTO professional_working_hours (professional_id, day_of_week, start_time, end_time)
SELECT p.id, schedule.day_of_week, TIME '09:00', TIME '18:00'
FROM professionals p
CROSS JOIN (VALUES
    ('MONDAY'), ('TUESDAY'), ('WEDNESDAY'), ('THURSDAY'),
    ('FRIDAY'), ('SATURDAY'), ('SUNDAY')
) AS schedule(day_of_week)
ON CONFLICT (professional_id, day_of_week) DO NOTHING;
