CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    professional_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_user_account_role CHECK (role IN ('ADMIN', 'PROFESSIONAL')),
    CONSTRAINT fk_user_account_professional FOREIGN KEY (professional_id) REFERENCES professionals(id)
);

CREATE TABLE professional_time_off (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    reason VARCHAR(300),
    CONSTRAINT fk_time_off_professional FOREIGN KEY (professional_id) REFERENCES professionals(id) ON DELETE CASCADE,
    CONSTRAINT ck_time_off_range CHECK (ends_at > starts_at)
);

CREATE INDEX idx_time_off_professional_range
    ON professional_time_off (professional_id, starts_at, ends_at);
